#!/usr/bin/env python3
"""Build and query feature/issue status indexes.

This script creates human-readable markdown indexes and supports quick lookups:
- python3 scripts/status_index.py build
- python3 scripts/status_index.py feature 019
- python3 scripts/status_index.py issue 12
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
import re
import subprocess
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.toml_compat import tomli


ROOT = REPO_ROOT
FEATURE_DIR = ROOT / "docs" / "features"
ISSUE_DIR = ROOT / "docs" / "issues"
STATUS_DIR = ROOT / "docs" / "status"
OVERRIDES_PATH = STATUS_DIR / "status-overrides.toml"
FEATURE_INDEX_PATH = STATUS_DIR / "features-index.md"
ISSUE_INDEX_PATH = STATUS_DIR / "issues-index.md"


@dataclass(frozen=True)
class StatusEntry:
    item_id: str
    title: str
    path: Path | None
    defined_on: str
    status: str
    implemented_on: str | None
    notes: str | None


def _safe_date(value: str | None) -> str:
    if not value:
        return "unknown"
    try:
        datetime.strptime(value, "%Y-%m-%d")
        return value
    except ValueError:
        return "unknown"


def _load_toml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return tomli.loads(path.read_text(encoding="utf-8"))


def _git_first_added_date(path: Path) -> str:
    try:
        proc = subprocess.run(
            [
                "git",
                "log",
                "--diff-filter=A",
                "--follow",
                "--format=%ad",
                "--date=short",
                "--",
                str(path),
            ],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return "unknown"
    if proc.returncode != 0:
        return "unknown"
    lines = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    if not lines:
        return "unknown"
    return lines[-1]


def _discover_features() -> dict[str, tuple[str, Path]]:
    found: dict[str, tuple[str, Path]] = {}
    pattern = re.compile(r"^(\d{3})-(.+)\.md$")
    for path in sorted(FEATURE_DIR.glob("*.md")):
        match = pattern.match(path.name)
        if not match:
            continue
        feature_id = match.group(1)
        title = path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip() or match.group(2)
        found[feature_id] = (title, path)
    return found


def _discover_issues() -> dict[str, tuple[str, Path]]:
    if not ISSUE_DIR.exists():
        return {}
    found: dict[str, tuple[str, Path]] = {}
    pattern = re.compile(r"^(\d{1,4})-(.+)\.md$")
    for path in sorted(ISSUE_DIR.glob("*.md")):
        match = pattern.match(path.name)
        if not match:
            continue
        issue_id = match.group(1)
        title = path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip() or match.group(2)
        found[issue_id] = (title, path)
    return found


def _build_entries(
    discovered: dict[str, tuple[str, Path]],
    override_section: list[dict[str, Any]],
) -> dict[str, StatusEntry]:
    overrides: dict[str, dict[str, Any]] = {}
    for item in override_section:
        entry_id = str(item.get("id", "")).strip()
        if not entry_id:
            continue
        overrides[entry_id] = item

    all_ids = sorted(set(discovered.keys()) | set(overrides.keys()))
    out: dict[str, StatusEntry] = {}
    for entry_id in all_ids:
        discovered_title, discovered_path = discovered.get(entry_id, (f"Item {entry_id}", None))
        override = overrides.get(entry_id, {})
        title = str(override.get("title", discovered_title)).strip() or discovered_title
        defined_on = _safe_date(str(override.get("defined_on", ""))) if override.get("defined_on") else (
            _git_first_added_date(discovered_path) if discovered_path else "unknown"
        )
        status = str(override.get("status", "defined")).strip() or "defined"
        implemented_on = (
            _safe_date(str(override.get("implemented_on", ""))) if override.get("implemented_on") else None
        )
        notes = str(override.get("notes", "")).strip() or None
        out[entry_id] = StatusEntry(
            item_id=entry_id,
            title=title,
            path=discovered_path,
            defined_on=defined_on,
            status=status,
            implemented_on=implemented_on,
            notes=notes,
        )
    return out


def _render_features(entries: dict[str, StatusEntry]) -> str:
    lines = [
        "# Features Index",
        "",
        "Generated by `python3 scripts/status_index.py build`.",
        "",
        "Status values:",
        "- `defined`: specification exists, implementation not marked complete",
        "- `implemented`: implemented and marked complete",
        "- `in_progress`: currently being implemented",
        "",
        "| ID | Feature | Defined On | Status | Implemented On | Spec |",
        "|---|---|---|---|---|---|",
    ]
    for entry_id in sorted(entries.keys()):
        item = entries[entry_id]
        spec = f"[{item.path.name}]({item.path.as_posix()})" if item.path else "-"
        lines.append(
            f"| {item.item_id} | {item.title} | {item.defined_on} | {item.status} | {item.implemented_on or '-'} | {spec} |"
        )
    lines.append("")
    lines.append("## Notes")
    for entry_id in sorted(entries.keys()):
        item = entries[entry_id]
        if item.notes:
            lines.append(f"- {item.item_id}: {item.notes}")
    if not any(item.notes for item in entries.values()):
        lines.append("- none")
    lines.append("")
    return "\n".join(lines)


def _render_issues(entries: dict[str, StatusEntry]) -> str:
    lines = [
        "# Issues Index",
        "",
        "Generated by `python3 scripts/status_index.py build`.",
        "",
        "Status values:",
        "- `open`: known issue, not fixed yet",
        "- `in_progress`: fix currently in progress",
        "- `implemented`: issue resolved",
        "",
        "| ID | Issue | Defined On | Status | Implemented On | Spec/Link |",
        "|---|---|---|---|---|---|",
    ]
    for entry_id in sorted(entries.keys(), key=lambda x: int(x) if x.isdigit() else x):
        item = entries[entry_id]
        spec = f"[{item.path.name}]({item.path.as_posix()})" if item.path else "-"
        lines.append(
            f"| {item.item_id} | {item.title} | {item.defined_on} | {item.status} | {item.implemented_on or '-'} | {spec} |"
        )
    if not entries:
        lines.append("| - | No issues tracked yet | - | - | - | - |")
    lines.append("")
    return "\n".join(lines)


def build_indexes() -> tuple[dict[str, StatusEntry], dict[str, StatusEntry]]:
    STATUS_DIR.mkdir(parents=True, exist_ok=True)
    override_data = _load_toml(OVERRIDES_PATH)
    feature_overrides = override_data.get("feature", [])
    issue_overrides = override_data.get("issue", [])
    if not isinstance(feature_overrides, list):
        feature_overrides = []
    if not isinstance(issue_overrides, list):
        issue_overrides = []

    features = _build_entries(_discover_features(), feature_overrides)
    issues = _build_entries(_discover_issues(), issue_overrides)

    FEATURE_INDEX_PATH.write_text(_render_features(features), encoding="utf-8")
    ISSUE_INDEX_PATH.write_text(_render_issues(issues), encoding="utf-8")
    return features, issues


def print_single(kind: str, entry_id: str) -> int:
    features, issues = build_indexes()
    table = features if kind == "feature" else issues
    item = table.get(entry_id)
    if item is None:
        print(f"{kind} {entry_id}: not found")
        return 1
    print(f"{kind} {entry_id}")
    print(f"title: {item.title}")
    print(f"defined_on: {item.defined_on}")
    print(f"status: {item.status}")
    print(f"implemented_on: {item.implemented_on or '-'}")
    print(f"path: {item.path.as_posix() if item.path else '-'}")
    if item.notes:
        print(f"notes: {item.notes}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="status_index")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("build", help="Build docs/status/features-index.md and issues-index.md")
    p_feature = sub.add_parser("feature", help="Show one feature status")
    p_feature.add_argument("id", help="Feature ID, e.g. 019")
    p_issue = sub.add_parser("issue", help="Show one issue status")
    p_issue.add_argument("id", help="Issue ID")

    args = parser.parse_args()
    if args.cmd == "build":
        features, issues = build_indexes()
        print(f"features indexed: {len(features)} -> {FEATURE_INDEX_PATH}")
        print(f"issues indexed: {len(issues)} -> {ISSUE_INDEX_PATH}")
        return 0
    if args.cmd == "feature":
        return print_single("feature", str(args.id).zfill(3))
    if args.cmd == "issue":
        return print_single("issue", str(args.id))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
